version: "3.8"
services:
  # PostgreSQL
  postgres:
    container_name: postgres
    build: ./postgres
    environment:
      POSTGRES_USER: process.env.POSTGRES_USER
      POSTGRES_PASSWORD: process.env.POSTGRES_PASSWORD
      POSTGRES_DB: process.env.POSTGRES_DB
      POSTGRES_HOST: process.env.POSTGRES_HOST
      POSTGRES_URI: process.env.DATABASE_URL
    ports:
      - "5432:5432"

  # # Redis
  # redis:
  #   container_name: redis
  #   image: redis
  #   ports:
  #     - "6379:6379"

  # Backend
  facerecognition_backend:
    # env_file:
    #   - ./.private/api-keys.env "Another way to insert env variables"
    container_name: backend
    build: ./
    volumes:
      - ./:/usr/src/facerecognition_backend
    command: npm start
    working_dir: /usr/src/facerecognition_backend
    ports:
      - "3000:3000"
    environment:
      POSTGRES_URI: process.env.DATABASE_URL
      # REDIS_URI: redis://redis:6379
    links:
      - postgres
